svd – forsvd
svd Interface
3 statements
Source File
public interface svd
Calls
Called by
Module Procedures
private pure subroutine svd_rel(A, U, S, VT, method)
Author
Seyed Ali Ghasemi
Calculates the singular value decomposition (SVD) of a matrix A.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
real(kind=rk), intent(out), dimension(:,:) :: U
real(kind=rk), intent(out), dimension(:) :: S
real(kind=rk), intent(out), dimension(:,:) :: VT
character(len=*), intent(in), optional :: method
Call graph
svd calls svd_rel
svd_rel calls gesdd_rel, gesvd_rel
lowrank calls svd
benchmark calls svd
test1 calls svd
test2 calls svd
test3 calls svd
compress_pixels calls lowrank
test4 calls lowrank
test5 calls compress_pixels