benchmark – forsvd
benchmark Program
27 statements
Source File
Uses
kinds
forsvd
fortime
Calls
Contents
Variables
A U VT S m n i ntests t
Source Code
benchmark
Variables
Type Attributes Name Initial
real(kind=rk), dimension(:, :), allocatable :: A
real(kind=rk), dimension(:, :), allocatable :: U
real(kind=rk), dimension(:, :), allocatable :: VT
real(kind=rk), dimension(:), allocatable :: S
integer :: m
integer :: n
integer :: i
integer :: ntests
type(timer) :: t
Source Code
program benchmark
   use kinds
   use forsvd, only: svd
   use fortime, only: timer
   implicit none
   real(rk), dimension(:, :), allocatable :: A, U, VT
   real(rk), dimension(:),    allocatable :: S
   integer                                :: m, n, i, ntests
   type(timer)                            :: t
   m = 1000
   n = 1000
   allocate(A(m,n), U(m,m), S(min(m,n)), VT(n,n))
   call random_number(A)
   A = A*10.0_rk
   ntests = 5
   call t%timer_start()
   do i = 1, ntests
      call svd(A, U,S,VT, 'gesvd')
   end do
   call t%timer_stop(nloops = ntests, message='Elapsed time (gesvd): ')
   call t%timer_start()
   do i = 1, ntests
      call svd(A, U,S,VT, 'gesdd')
   end do
   call t%timer_stop(nloops = ntests, message='Elapsed time (gesdd): ')
   deallocate(A, U, S, VT)
end program benchmark
Call graph
benchmark calls svd
svd calls svd_rel
svd_rel calls gesdd_rel, gesvd_rel