test5 – forsvd
test5 Program
13 statements
Source File
Uses
forsvd
Calls
Variables
Type Attributes Name Initial
type(pixel) :: px
Source Code
program test5
   use forsvd, only: pixel
   implicit none
   type(pixel) :: px
   px%nrow = 356
   px%ncol = 238
   call px%image_to_pixels(image_name='pixel/John_W_Backus.jpg', file_name='pixel/John_W_Backus.txt')
   call px%load_pixels(file_name='pixel/John_W_Backus.txt')
   call px%compress_pixels(rank=10)
   call px%save_pixels(file_name='pixel/John_W_Backus_com.txt')
   call px%pixels_to_image(image_name='pixel/John_W_Backus.jpg', file_name='pixel/John_W_Backus.txt')
   call px%dlloc()
end program test5
Call graph
test5 calls compress_pixels, deallocate_pixel, image_to_pixels, load_pixels, pixels_to_image, save_pixels
compress_pixels calls lowrank
lowrank calls svd
svd calls svd_rel
svd_rel calls gesdd_rel, gesvd_rel